#!/bin/bash

# scp *.html 72c1de6f9c9b4d029b008ebbdb927f73@compute6-us.sagemath.com:webpage/
# scp active-CV.tex active-CV.pdf 72c1de6f9c9b4d029b008ebbdb927f73@ssh.cocalc.com:webpage/
cp active-CV-short.pdf Jephian-CV.pdf
cp active-CV-long.pdf Jephian-CV-full.pdf
scp active-CV.tex Jephian-CV.pdf Jephian-CV-full.pdf 72c1de6f9c9b4d029b008ebbdb927f73@ssh.cocalc.com:webpage/
