#!/bin/bash

bibtool -o pre-accepted.bib -x active-CV.1.aux 
bib2bib Coauthors.bib pre-accepted.bib > accepted.bib
bibtex2html -nodoc -nofooter -nf pdf "pdf" -revkeys -nobibsource accepted.bib
rm pre-accepted.bib
