#!/bin/bash

aux2bib active-CV.4.aux > pre-plenary.bib
bib2bib Coauthors.bib pre-plenary.bib > plenary.bib
bibtex2html -nodoc -nofooter -nf video "video" -nf pdf "pdf" -revkeys -nobibsource plenary.bib
rm pre-plenary.bib
